### ISSUE TITLE
Change the request and response validation to use paths mapped to matchers

### ISSUE THREAD

**Issue by uglyog** [pact-foundation/pact-ruby#1]
The current validation of the requests and response bodies is by comparison of the whole expected body. It does allow more to be in the actual body, but it is awkward when the bodies get large.

One idea id to allow paths to be mapped to a matcher. This would work in a XPath or JSON Path style. That way you can have a number of paths to execute the matcher against.

**Comment by YOU54F** [comment]
Closing this as matching based on the 2.0 spec has been implemented

https://github.com/pact-foundation/pact-specification/tree/version-2?tab=readme-ov-file#supported-matchers
