### ISSUE TITLE
Wiki Type Matching example is incorrect

### ISSUE THREAD

**Issue by mycargus** [pact-foundation/pact-ruby#120]
The `Type matching` section of the wiki contains a syntax error. Also, in my opinion, another code example is needed.

Proposed changes: https://github.com/mycargus/pact-wiki/commit/5897727b28eaca816c5244ec96d5e278388e4ffb

I love Pact. Thanks for your hard work!

**Comment by bethesque** [comment]
Have commented on your commit, thank you!

**Comment by mycargus** [comment]
Glad to help!

Question: How does one submit a pull request to the pact repo wiki?  From what I can find, github doesn't provide that functionality for wiki contributions. 😞

**Comment by uglyog** [comment]
These wiki pages has been replicated at https://docs.pact.io/documentation/matching.html. You can submit a PR against the github project https://github.com/pact-foundation/pact-foundation.github.io

**Comment by mycargus** [comment]
hmm... the Matching doc https://docs.pact.io/documentation/matching.html isn't in the repo https://github.com/pact-foundation/pact-foundation.github.io  😕

**Comment by uglyog** [comment]
Oh, yeah, It's in the test branch.

**Comment by mycargus** [comment]
ah, there it is 😄 thanks!

**Comment by bethesque** [comment]
I've updated the Ruby wiki. Closing this one.
