### ISSUE TITLE
URL escape spaces in markdown index

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby#135]
https://github.com/realestate-com-au/pact/blob/master/lib/pact/doc/markdown/index_renderer.rb#L24

**Comment by olleolleolle** [comment]
Updated link:
https://github.com/pact-foundation/pact/blob/master/lib/pact/doc/markdown/index_renderer.rb#L24

**Comment by YOU54F** [comment]
Fixed in https://github.com/pact-foundation/pact-ruby/commit/6af19d51693b2431621cbae914fe8a39e89c1ff5
