### ISSUE TITLE
Allow rack-test 1.x?

### ISSUE THREAD

**Issue by ivan-kolmychek** [pact-foundation/pact-ruby#164]
As for [1.26.0](https://rubygems.org/gems/pact/versions/1.26.0), rack-test is locked to `~> 0.6`, which matched all versions up to `0.8.3`.

The newest version is 1.0.0, since it contains some [breaking changes](https://github.com/rack-test/rack-test/blob/master/History.md#100--2018-03-27).

Shoud version constraint be updated?

**Comment by bethesque** [comment]
> Always set CONTENT_TYPE for non-GET requests (Per Lundberg #223)

That breaking change may affect us, as rack-test is used to replay the requests against the mock service, and there is nothing to stop pact users mocking a non-get request with no content type. I'll have to investigate the code to see what the impact is. If you're interested in taking a look and reporting back, that would be awesome.

**Comment by BookOfGreg** [comment]
Referencing the PR for convenience:
https://github.com/rack-test/rack-test/pull/223

**Comment by bethesque** [comment]
Have updated this to allow 1.1.0
