### ISSUE TITLE
Remove RSpec dependency

### ISSUE THREAD

**Issue by edejong** [pact-foundation/pact-ruby#173]
The documentation states that it's possible to use MiniTest instead of RSpec which is great, but RSpec is a runtime dependency of pact so I cannot add Pact to my project without pulling in everything related to RSpec. Is this really necessary?

**Comment by bethesque** [comment]
On the provider side, RSpec is used to dynamically generate the pact verification tests, so even though you can use minitest on the consumer side, yes, RSpec is a necessary dependency, as the consumer and provider code are in the same gem. Sorry, but it shouldn't affect any runtime behaviour. Let me know if it does.

**Comment by edejong** [comment]
That makes total sense, thanks for explaining. It's not really that much of a problem per se, more the fact that we in general try to keep our gem count for our projects from exploding. I'm wondering, could the dependency be handled at runtime? As in just document that people need to install a certain version of RSpec when they use the provider side and detect this at runtime, or throw a meaningful error when it's being used but not present? For example how an ORM doesn't need a specific DB adapter to be installed but only works when you do. I'd be happy to try and make a PR for that if this is something you could get behind at all? If not I'll drop it and merrily continue using the gem as is

**Comment by bethesque** [comment]
That would make sense for the consumer side, but it would be strange on the provider side, where you would still have to install rspec even if you were using mini-test. I'm also loath to make breaking changes for all the existing users. If it's that serious an issue for you, you could always fork the repo, and remove the dependency.

**Comment by edejong** [comment]
Ok, well consider it a feature request to either split up the gem into a consumer and a producer or to loosen the dependency on RSpec (could even make an adapter for MiniTest to remove the dependency on the Provider side as well), and do with it as you will. It certainly wouldn't be something for a minor version bump :)
If you ever decide to go that path I would be happy to put some work into it myself but for now thanks for your answers.
