### ISSUE TITLE
Message for duplicate interaction should specify that the headers/body/path are differerent

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby#18]
``` shell
RuntimeError:
       Interaction with same description (a request retrieve a committed revenue sync) and provider state (a committed-revenue-sync exists with ID 123) already exists
```

Duplicate description/provider state is allowed so long as the entire interaction itself is identical.

Suggested new message:

An interaction with same description (a request retrieve a committed revenue sync) and provider state (a committed-revenue-sync exists with ID 123) has already been used, however, its has different request and/or response details. Please use a new description or provider state.

**Comment by YOU54F** [comment]
Completed in https://github.com/pact-foundation/pact-mock_service/commit/b238f2adca96ef99b7cbd599a53cb32056ffc49c

and released in 0.7.1 of pact-mock_service https://github.com/pact-foundation/pact-mock_service/releases/tag/0.7.1
