### ISSUE TITLE
Allow to specify the host for a mock service

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [pact-foundation/pact-ruby#186]
Currently only the `port` can be specified for a `MockService`. The `host` is hard coded to `localhost`. 

https://github.com/pact-foundation/pact-ruby/blob/866d89d197f315f915c41a01bc405057ba4b530a/lib/pact/consumer/configuration/mock_service.rb#L54-L61

The `AppManager` [itself](https://github.com/pact-foundation/pact-mock_service/blob/master/lib/pact/mock_service/app_manager.rb#L23-L36) also doesn't allow to specify URIs other than `http://localhost`.

````ruby
def register_mock_service_for(name, url, options = {})
   uri = URI(url)
   raise "Currently only http is supported" unless uri.scheme == 'http'
   raise "Currently only services on localhost are supported" unless uri.host == 'localhost'
   uri.port = nil if options[:find_available_port]

   app = Pact::MockService.new(
     name: name,
     log_file: create_log_file(name),
     pact_dir: pact_dir,
     pact_specification_version: options.fetch(:pact_specification_version)
   )
   register(app, uri.port)
end
````

Is there a good reason for that restriction? Our CI environment provides dependencies (other services) on other hosts than `localhost`.
Are there any plans to changes this?

**Comment by bethesque** [comment]
> Is there a good reason for that restriction?

Time. 

I've done it now, but I have to be honest, I haven't tested it on anything other than 127.0.0.1 and 0.0.0.0 (time again). Please try it and let me know how you go.

**Comment by bheemreddy181** [comment]
Can some one help me understand how to provide the host name here ? In the pact_helper.rb ?

**Comment by bethesque** [comment]
Yes, in the pact_helper.rb
https://github.com/pact-foundation/pact-ruby/wiki/Creating-pacts
