### ISSUE TITLE
[QUESTION] : customize provider host on consumer side

### ISSUE THREAD

**Issue by bheemreddy181** [pact-foundation/pact-ruby#188]
is this how I mock the host for provider mock on the consumer side

```
Pact.service_consumer "sampler" do
  has_pact_with "sample" do
    mock_service :payments_service do
      host sample.test.dev
      port 1234
    end
  end
end
```

**Comment by bethesque** [comment]
Is this a question? Your host needs quotes around it btw.

**Comment by bethesque** [comment]
You need quotes around the host value (`"sample.test.dev"`). Are you starting up your own mock service on sample.test.dev? If you are, then you need to also set `standalone true`.

@bheemreddy181 I don't understand your usecase. Can you please explain it fully so I can help you properly?

**Comment by bheemreddy181** [comment]
We usually have API URL's store in dev yml's which we want to use similar to PROD. I am trying to re-use those endpoints so that I don't have to do any change for the Interactor to use the mock service what I am pointing to while hitting the API on DEV. 

So,I was thinking to use the same endpoint on PACT mock as well

**Comment by bethesque** [comment]
Typically, you'd have a separate yml config for the pact tests, using localhost. But if you can get it working, then good luck! How are you going to get the mock service to run at that domain?
