### ISSUE TITLE
provider_state set_up not executing after 1.36.0

### ISSUE THREAD

**Issue by lkudyba** [pact-foundation/pact-ruby#200]
Hey, @bethesque! I'm trying to upgrade `pact` in my rails project and it looks like in `v1.36.0` all my `set_up` in `provider_state` is not executed anymore. I tried to look through the changes introduced in `1.36.0` but unfortunately I couldn't find what's wrong. Do you have any idea what could be the issue here? Have there been any changes to the DSL that are not documented?

My code looks exactly like in the examples:
```ruby
Pact.provider_states_for 'some-app' do
  provider_state 'there are xyz' do
    set_up do
```

I'm using Rails 5

**Comment by bethesque** [comment]
That's a worry. Can you please provide a code example to replicate this on?

**Comment by lkudyba** [comment]
Hey @bethesque thanks for your quick response! For now I decided to leave this issue as it's not crucial for my project and trying to replicate my app's setup could be too much effort. I'm closing this issue not to clutter this repo, but I'll try to resolve this in the future, thanks!
