### ISSUE TITLE
Ruby not found error

### ISSUE THREAD

**Issue by JoshKeegan** [pact-foundation/pact-ruby#207]
Hi,
I'm trying to run some consumer tests in a docker container, but I'm getting the following error:
```
[2020-02-10T17:03:24.939Z] ERROR: pact-node@8.6.2/186 on bac57364dd03: 
Pact Binary Error: ./standalone/linux-x64-1.69.0/bin/pact-mock-service: exec: line 28: /home/node/app/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.69.0/lib/ruby/bin/ruby: not found
```

Has anyone come across this before?

It looks like there is a bash script in the location the error specifies, but then within that script it calls out to other scripts, so I'm guessing the actual error is being generated somewhere further down the stack.

**Comment by JoshKeegan** [comment]
Sorry, I opened this on the wrong repo!

**Comment by mefellows** [comment]
@JoshKeegan have you read the Alpine section of the docs on docs.pact.io? It's likely a missing dependency

**Comment by JoshKeegan** [comment]
Thanks @mefellows, that was it!

**Comment by mefellows** [comment]
Awesome, no probs!
