### ISSUE TITLE
Failed verification of pending Pact fails provider test suite when other non-pending Pacts are successfully verified in the same suite

### ISSUE THREAD

**Issue by tylerncollins** [pact-foundation/pact-ruby#223]
### Relevant versions
- pact-ruby: 1.54.0
- pact-broker: 2.60.1.0

### Steps to reproduce
- Have 2 pacts in a pact broker, where 1 is pending and 1 is not
- Have appropriate provider state setup for the non-pending pact (so the verification will pass)
- Do not have appropriate provider state setup for the pending pact (so that the verification will fail)
- Run the provider verification tests with `enable_pending true`

### Observed Issue
The provider test suite fails due to the failed verification of the pending pact. Caused by: https://github.com/pact-foundation/pact-ruby/blob/eb1a5893cd8670397cfa93dbd10d618f8f4b6d3c/lib/pact/provider/pact_spec_runner.rb#L162

### Desired Behavior
The provider test suite only fails when non-pending (previously verified) pacts fail the verification test. Failed verification of pending pacts do not cause the provider test suite to fail.

**Comment by bethesque** [comment]
I had a good dig around today, and while I haven't got a fix yet, I have an idea of how to do it. Got to make sure it fails correctly for the non-pending pacts.
