### ISSUE TITLE
Request omits [] in queries after 1.55.6

### ISSUE THREAD

**Issue by mkarganov** [pact-foundation/pact-ruby#228]
Hi, looks like the recent upgrade broke some query params format during pact verification. 
Example:
in pact broker the request is defined correctly:
`"query": "/receipts?fruits[]=mango&fruits[]=apple"`

whether during pact verification it is sent like:
`with GET /receipts?fruits=mango&fruits=apple`

So the params are not treated as an array.
Looks like the fix was done already: https://github.com/pact-foundation/pact-support/commit/4e9ca9c1f9025574dd2ca40185ec8174e4925a34 
But after updating the problem still persists. I am not on Rails btw.

**Comment by benpjohnson** [comment]
We are seeing something similar on a Rails / Grape project

**Comment by bethesque** [comment]
Sorry, the change was try to and fix the warnings about the query matchers that have been there for 4 years. Lock pact-support to 1.15.1 until I can work out how to make it work for every situation.

**Comment by bethesque** [comment]
FYI, have this scheduled in for my OSS day on Wednesday.

**Comment by bethesque** [comment]
Ok, update to 1.16.4, and everything should be happy again.

**Comment by mkarganov** [comment]
Thank you! All is good!
