### ISSUE TITLE
Chore: migrate away from TravisCI

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-ruby#231]
TravisCI (org) is dropping support for OSS builds at the end of this month, meaning they must be transferred to travis-ci.com, which uses a credit system. Builds may fail (and already are) if the number of credits is exhausted within the month.

We are recommending switching to GH Actions, but the choice of CI provider is up to the project maintainer.

See also:

https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567/5

**Comment by YOU54F** [comment]
done, will become x-plat tested with #292
