### ISSUE TITLE
Naming collision with term-ansicolor gem

### ISSUE THREAD

**Issue by Benjaminpjacobs** [pact-foundation/pact-ruby#253]
I am attempting to utilize this gem for contract testing in a rails application and am running into a significant namespace collision between an active record `Term` model and the `Term` namespace that is injected from the `term-ansicolor` gem used for string colorization. 

I see from the git history that the colorization gem was already [swapped out once](https://github.com/pact-foundation/pact-ruby/commit/f7910a1f2d957d08893fb0eb3417e9de3d205609) for a similar sort of issue. Would maintainers be amenable to a different ANSI colorization gem, like [Rainbow](https://github.com/sickill/rainbow), that may be less likely to collide with common class names? I would be happy to submit PRs to the required libraries for this change.

**Comment by bethesque** [comment]
This is out now I believe.
