### ISSUE TITLE
Document wait_for_interactions

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby#26]
And make the params optional

**Comment by YOU54F** [comment]
params made optional in 

https://github.com/pact-foundation/pact-ruby/commit/ca883a8b17fe50f9b53ada6cff291bec801490ee (version 1.3.2 of pact-ruby)

example usage shown in integration spec

https://github.com/pact-foundation/pact-ruby/blob/master/spec/integration/consumer_async_request_spec.rb#L34

can't see anyone using it in the wild

https://github.com/search?q=wait_for_interactions&type=repositories
