### ISSUE TITLE
Pact v3 specification implementation for Pact Ruby

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [pact-foundation/pact-ruby#266]
Please implement the [pact v3 specification](https://github.com/pact-foundation/pact-specification/tree/version-3) for Ruby (MRI and JRuby).

This ticket is a starting point. Please feel free to convert it to a GitHub project or a milestone.

**Comment by YOU54F** [comment]
ps we don't officially support jruby, it hasn't been tested in many moons, and therefore support _may_ be dropped completely if it doesn't work with ffi interop with the pact_ffi native library. see #317
