### ISSUE TITLE
Verify when the provider has no matching Pacts

### ISSUE THREAD

**Issue by jmortlock** [pact-foundation/pact-ruby#272]
We are currently in the process of rebuilding our pact broker database (moving to Postgres) so all our consumers/providers need to to republished and verified.

It would be nice that if pact broker has no matching pacts to verify that it does not hard fail.

Currently you hit the following line of code:
[        raise "Please configure a pact to verify" if pact_urls.empty?](https://github.com/pact-foundation/pact-ruby/blob/bb0ddca700f9aeb05c9f78d214cdbe2962a50786/lib/pact/cli/run_pact_verification.rb#L75)

Workaround we are currently using is to add a custom envvar that we check during build to disable verification checking.

**Comment by bethesque** [comment]
The CLI has this option, so it should be easy to add.
