### ISSUE TITLE
"Ignoring unsupported combine AND for path" on every property

### ISSUE THREAD

**Issue by jamesarosen** [pact-foundation/pact-ruby#276]
My consumer uses [pact-js@10.x](https://github.com/pact-foundation/pact-js) using the v2 matchers:
```ts
import { Matchers } from '@pact-foundation/pact'

const projectMatch = {
  name: Matchers.string('My Project'),
}
```

When I run the provider verification using pact-ruby@1.63.0, I get
```
WARN: Ignoring unsupported combine AND for path $['name']
```

I get this same warning for every string matcher.

My pact `.json` file has
```
"pactSpecification": {
  "version": "3.0.0"
}
```
so this warning may come from a mismatch between using v2 matchers with a v3 spec.

**Comment by YOU54F** [comment]
Hey, you need to use the `Pact` not `PactV3` interface, if using `v2` matchers.

`v3` matchers are applicable for `v3` verifier codebases. You can use the pact verifier cli as an interim until the Ruby codebase supports `v3` and `v4` pacts

We should probably detect that and inform on the consumer side

**Comment by jamesarosen** [comment]
The warning does go away if I do this:
```ts
import { PactV3, SpecificationVersion } from "@pact-foundation/pact";

new PactV3({
  spec: SpecificationVersion.SPECIFICATION_VERSION_V2,
  // other options
});
```

That way, I get to keep using the V3 `Pact` API in JS. Though I have to be careful because
```ts
.given('an alligator exists', { name: 'Tom' })
```
is totally valid but emits just `"an alligator exists"` to the spec file since it's a v2 spec.
