### ISSUE TITLE
Set order of interactions in Pact file

### ISSUE THREAD

**Issue by patrickbadleyupstart** [pact-foundation/pact-ruby#279]
This is a duplicate of an [old issue](https://github.com/pact-foundation/pact-ruby/issues/48) that was marked as resolved and closed, but I am still seeing this behavior.  When I run my rspec tests for my consumer the generated pactfile will intermittently get written with it's interactions in a different order.  This makes for confusing git change history.  Is it possible that the interaction ordering was broken somehow?  I'm not sure what the best solution would be, but perhaps ordering interactions by description and then provider state?

Gem versions:
```
    pact (1.63.0)
      pact-mock_service (~> 3.0, >= 3.3.1)
      pact-support (~> 1.16, >= 1.16.9)
      rack-test (>= 0.6.3, < 3.0.0)
      rspec (~> 3.0)
      term-ansicolor (~> 1.0)
      thor (>= 0.20, < 2.0)
      webrick (~> 1.3)
```

**Comment by bethesque** [comment]
You can set the order to `alphabetical` https://github.com/pact-foundation/pact-mock_service/blob/master/lib/pact/consumer_contract/consumer_contract_decorator.rb#L33
