### ISSUE TITLE
Set order of interactions in pact file

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby#48]
When rspec runs with random order, the interactions are added to the pact file in the random order, and hence, the pact file changes significantly each time, and it is hard to see what the actual genuine changes are. Allow the order of the interactions to be written consistently.

**Comment by sonjapeterson** [comment]
@bethesque I've run into this issue with randomly ordered spec runs causing noise in my pact files even when nothing has changed, and I'd be happy to try working on a solution. Do you have any existing ideas about what an implementation for writing the order consistently might look like?

**Comment by bethesque** [comment]
@amalkov is just working on something at the moment to set the order of the interactions so they don't change each time (while maintaining backwards compatibility for @allavena). It's here: https://github.com/realestate-com-au/pact/pull/104/files

**Comment by allavena** [comment]
That project is dead. So please don't saddle yourself with backwards
compatibility just for me!

The only trick I'm aware I'm using is to make some pacts be parameterised,
and have that param value in its title (which I think is as basic as it
gets)

André

**Comment by sonjapeterson** [comment]
@bethesque That's great, thanks!

**Comment by bethesque** [comment]
This is now implemented.
