### ISSUE TITLE
Authentication tokens/step in pact.

### ISSUE THREAD

**Issue by stefan-lz** [pact-foundation/pact-ruby#49]
So at the moment we are having to modify the pact.json files before running pact. This is for inserting authentication tokens with expiry in about 2 hours into the pacts.

```
pacts = File.join(File.dirname(File.expand_path(__FILE__)), '../src/test/resources/pacts/*.json')
Dir.glob(pacts).each do |f|
  text = File.read(f)
  output_of_gsub = text.gsub(/\"Authorization\"\s*:\s*\".+\"/) { "\"Authorization\": \"ioof-token #{token}\"" }
  File.open(f, "w") { |file| file.puts output_of_gsub }
end
```

It would be good to be able to nicely insert/modify headers of the request before they are sent without modifying the pact files.

Cheers,

**Comment by eskimoquinn** [comment]
@bethesque I have found a few examples of how to modify the headers, like your example above, can the request body be similarly modified? If so, it is not apparent to me how to do that. Any suggestions?

**Comment by bethesque** [comment]
Yes, using the same approach (though can I stress, it is NOT recommended!) What problem are you trying to solve? Before we go down the dirty hack route, let's see if there's another way we can solve it.

**Comment by bethesque** [comment]
Btw, for anyone reading this issue in the future, there is a `--custom-provider-header` option you can use in the pact-provider-verifier now. See docs here: https://github.com/pact-foundation/pact-provider-verifier#setting-a-custom-authentication-header

**Comment by eskimoquinn** [comment]
@bethesque the reason I asked this question about modifying body is because we are trying to test services that wrap an externally hosted database. We need to test deleting an entity, however, we can only delete by a uniquely generated entity ID. We cannot setup the entity with a specific identity. Thus we need to modify the ID of the entity before making the call against the real service. I see that the JVM provider has a way to do this, but we would really like to do this in the pact-provider-proxy for Ruby. We still have this problem by the way and it is leading to people not writing tests for these endpoints or questioning pact in general. Any thoughts?

**Comment by bethesque** [comment]
Yes. I've just written some rack middleware to allow the request to be modified in transit. There will be a more elegant implementation of this in the v4 spec, but for now, I would use a hardcoded token that you replace in this middleware. 

The way you use it is to create a middleware class that implements `Pact::ProviderVerifier::CustomMiddleware` and modifies the [Rack env](https://www.rubydoc.info/github/rack/rack/file/SPEC). The Rack env is just a big flattened hash of all the request information. I've augmented it with the provider states information.

```
class MyMiddleware < Pact::ProviderVerifier::CustomMiddleware
  def initialize app
    @app = app
  end

  def call env 
    provider_states = provider_states_from(env)
    provider_state_name = provider_states.any? && provider_states.first.name
    puts "The provider state name is '#{provider_state_name}'"
    env['PATH_INFO'].gsub('HARDCODED_ID', 'DYNAMIC_ID') # Obviously, this has to be gotten from somewhere dynamically
    @app.call(env)
  end
end
```

If writing code in ruby is not your thing, you could create a proxy app in the language of your choice that modifies the request appropriately.

**Comment by eskimoquinn** [comment]
Thanks @bethesque we are trying this out.

**Comment by YOU54F** [comment]
Closing this as per the comments here

https://github.com/pact-foundation/pact-ruby/issues/49#issuecomment-339796408
