### ISSUE TITLE
Add instruction about showing full backtrace when provider verification fails

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby#59]

**Comment by YOU54F** [comment]
This is complete

https://github.com/pact-foundation/pact-ruby/blob/17ce64bd2d43841144b6810a36746654f6fb8560/lib/pact/templates/help.erb#L9

Introduced in commit 

https://github.com/pact-foundation/pact-ruby/commit/43aa930fb681ce3cbe8be17bf1661f6bf3f1d597

First released in 

https://github.com/pact-foundation/pact-ruby/releases/tag/v1.5.0
