### ISSUE TITLE
Fix command to rerun

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby#76]
Currently displaying as

bundle exec rake pact:verify:at[#Pact::Provider::PactURI:0x00000001dfa218] PACT_DESCRIPTION="a request for the index" PACT_PROVIDER_STATE="" # A request for the index

**Comment by lifeifei** [comment]
Hi Beth,

This was introduced when I was working on the basic auth feature. Sorry about this.  I just saw this issue today. I've fixed it and will create a pull request soon.
